### ISSUE TITLE
Make it more obvious that a search has happened

### ISSUE THREAD

**Issue by axelson** [yeraydiazdiaz/shoutouts.dev#76]
Right now if you search for a project that doesn't exist on shoutouts (I used react), then search for another project that doesn't exist (I used phoenix) then nothing on the page changes except the text you typed, which makes it difficult to be sure that a search has actually happened.

There's two main things that could change, the error message. Instead of:
> Sorry, no projects match your query
It could be
> Sorry, no projects matched your query of `react`

Also the query parameter `q` in the URL bar should change as well

**Comment by yeraydiazdiaz** [comment]
Yep, good point 👍🏻
